import { Award, BookOpen, CalendarDays, ExternalLink, Heart, Mic2, Music2, Sparkles } from "lucide-react";

const facts = [
  {title:"A estreia",kicker:"4 DE NOVEMBRO DE 2013",text:"Steven Universe começou a ser exibido nos Estados Unidos em novembro de 2013.",source:"Warner Bros. Discovery",url:"https://www.discoveryjapan.jp/cartoonnetwork/stevenuniverse/",Icon:CalendarDays,size:"fact-feature"},
  {title:"Criado por Rebecca Sugar",kicker:"CRIAÇÃO",text:"A página oficial do Peabody credita Rebecca Sugar como criadora e produtora executiva da série.",source:"Peabody Awards",url:"https://peabodyawards.com/award-profile/steven-universe/",Icon:Sparkles,size:"fact-tall"},
  {title:"Inspirado em um irmão",kicker:"BASTIDORES",text:"Rebecca contou à Television Academy que pensou imediatamente no irmão mais novo, Steven Sugar, ao conceber a série.",source:"Television Academy",url:"https://www.televisionacademy.com/features/news/mix/brothere28099s-keeper/brothere28099s-keeper",Icon:Heart,size:"fact-standard"},
  {title:"Uma equipe musical",kicker:"TRILHA SONORA",text:"Os créditos de produção registram Aivi & Surasshu e Rebecca Sugar entre os compositores.",source:"Peabody Awards",url:"https://peabodyawards.com/award-profile/steven-universe/",Icon:Music2,size:"fact-wide"},
  {title:"Reconhecida pela Academia",kicker:"EMMY",text:"A Television Academy registra seis indicações e uma vitória para Steven Universe.",source:"Television Academy",url:"https://www.televisionacademy.com/shows/steven-universe",Icon:Award,size:"fact-standard"},
  {title:"Peabody em 2018",kicker:"VENCEDORA",text:"O prêmio destacou a inteligência emocional da série e sua exploração de identidade e comunidade.",source:"Peabody Awards",url:"https://peabodyawards.com/award-profile/steven-universe/",Icon:Award,size:"fact-feature"},
  {title:"Vozes da versão original",kicker:"ELENCO",text:"Os créditos incluem Zach Callison, Estelle, Michaela Dietz e Deedee Magno Hall entre o elenco principal.",source:"Peabody Awards",url:"https://peabodyawards.com/award-profile/steven-universe/",Icon:Mic2,size:"fact-standard"},
  {title:"História pelo olhar de Steven",kicker:"NARRATIVA",text:"Rebecca explicou que a equipe escrevia o mundo ao redor de Steven e, depois, aquilo que ele era capaz de compreender.",source:"Television Academy",url:"https://www.televisionacademy.com/features/news/mix/brothere28099s-keeper/brothere28099s-keeper",Icon:BookOpen,size:"fact-wide"},
];

export function CuriosityExplorer(){return <section className="facts-section" id="curiosidades"><div className="section"><div className="section-heading facts-heading"><div><span className="eyebrow"><BookOpen size={14}/> FATOS VERIFICADOS</span><h2>Notas de produção,<br/>música e impacto</h2></div><p>Uma composição editorial baseada em fontes oficiais e institucionais.</p></div><div className="facts-editorial">{facts.map(({Icon,...fact},index)=><article className={`fact-note ${fact.size}`} key={fact.title}><span className="fact-index">{String(index+1).padStart(2,"0")}</span><Icon/><small>{fact.kicker}</small><h3>{fact.title}</h3><p>{fact.text}</p><a href={fact.url} target="_blank" rel="noreferrer">Fonte: {fact.source}<ExternalLink/></a></article>)}</div></div></section>}
